---
- name: Execute PowerShell scripts on a Windows host in a specific order
  hosts: win  # Adjust this to match your inventory
  gather_facts: no

  tasks:
#Copy from 1.137
  - name: Delete the mapped drive Z
    community.windows.win_mapped_drive:
        letter: Z
        path: \\<IP1>\backup
        state: absent
    when: inventory_hostname == 'hostname1'

  - name: Delete the mapped drive X
    community.windows.win_mapped_drive:
      letter: X
      path: \\<IP2>\kopia
      state: absent
    when: inventory_hostname == 'hostname1'

  - name: Create mapped drive Z
    community.windows.win_mapped_drive:
      letter: Z
      path: \\<IP1>\backup
      state: present
      username: 'login'
      password: 'password'
    when: inventory_hostname == 'hostname1'
    vars:
        ansible_become: yes

  - name: Create mapped drive X
    community.windows.win_mapped_drive:
      letter: X
      path: \\<IP2>\kopia
      state: present
      username: 'login'
      password: 'password'
    when: inventory_hostname == 'hostname1'
    vars:
        ansible_become: yes

  - name: Run Weekly Copy
    ansible.windows.win_command: powershell.exe -ExecutionPolicy Bypass -File C:\Skrypty\Backup_w\2024\main.ps1
    when: inventory_hostname == 'hostname1'
    vars:
        ansible_become: yes

  - name: Delete the mapped drive Z
    community.windows.win_mapped_drive:
      letter: Z
      path: \\<IP1>\backup
      state: absent
    when: inventory_hostname == 'hostname1'
    vars:
        ansible_become: yes

  - name: Delete the mapped drive X
    community.windows.win_mapped_drive:
      letter: X
      path: \\<IP2>\kopia
      state: absent
    when: inventory_hostname == 'hostname1'
    vars:
        ansible_become: yes

#Copy from 1.101
  - name: Create mapped drive X
    community.windows.win_mapped_drive:
      letter: X
      path: '\\<IP2>\kopia'
      state: present
      username: 'login'
      password: 'password'
    when: inventory_hostname == 'hostname2'
    vars:
      # become - to mount network device
      ansible_become: yes

  - name: Execute Script 1 (1 - Delete oldest folder.ps1)
    ansible.windows.win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Skrypty\Kopia_tygodniowa\1 - Delete oldest folder.ps1"
    when: inventory_hostname == 'hostname2'
    vars:
      # become - script requires elevated permissions
      ansible_become: yes

  - name: Execute Script 2 (2 - Archivelogs.ps1)
    ansible.windows.win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Skrypty\Kopia_tygodniowa\2 - Archivelogs.ps1"
    when: inventory_hostname == 'hostname2'
    vars:
      # become - script requires elevated permissions
      ansible_become: yes

  - name: Execute Script 3 (3 - HARTERP.ps1)
    ansible.windows.win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Skrypty\Kopia_tygodniowa\3 - HARTERP.ps1"
    when: inventory_hostname == 'hostname2'
    vars:
      # become - script requires elevated permissions
      ansible_become: yes

  - name: Execute Script 4 (4 - ERPARCH.ps1)
    ansible.windows.win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Skrypty\Kopia_tygodniowa\4 - ERPARCH.ps1"
    when: inventory_hostname == 'hostname2'
    vars:
      # become - script requires elevated permissions
      ansible_become: yes

  - name: Delete the mapped drive X
    community.windows.win_mapped_drive:
      letter: X
      path: '\\<IP2>\kopia'
      state: absent
    when: inventory_hostname == 'hostname2'
